{% set name = "kartograf" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kartograf-{{ version }}.tar.gz
  sha256: 2f1f7e7d3fcfca114f092bb2b99480af78112ac088ed3f870da2f987a9c2ae46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61.0
    - versioningit
  run:
    - numpy
    - python >=3.9
    - rdkit
    - scipy
    - gufe

test:
  imports:
    - kartograf
  requires:
    - pip
    - pytest
    - py3Dmol
  commands:
    - pytest --pyargs kartograf

about:
  home: https://github.com/OpenFreeEnergy/kartograf
  summary: This is a package for setting up FE-calculations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dwhswenson
    - ialibay
    - mikemhenry
    - richardjgowers
    - riesben
