{% set name = "kartograf" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kartograf-{{ version }}.tar.gz
  sha256: adea6c3e1c2fb7a233da15b31a8898b0f913016ed22ad42007faf5ab87495c84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61.0
    - versioningit
  run:
    - networkx
    - numpy
    - python >=3.9
    - rdkit
    - scipy

test:
  imports:
    - kartograf
  requires:
    - pip

about:
  home: https://github.com/OpenFreeEnergy/kartograf
  summary: This is a package for setting up FE-calculations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dwhswenson
    - ialibay
    - mikemhenry
    - richardjgowers
    - riesben
